project:
  type: website
  output-dir: docs
  render:
  - "*.qmd"
  - "ipynb/*.ipynb"
  - "!CONTRIBUTIONG.md"
  - "!LICENSE.md"

website:
  title: "Fundamentals of Machine Learning"
  favicon: assets/mines_logo.png
  search: true
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: Home    
      - href: course_schedule.qmd
      - href: about.qmd
    right:
      - icon: github
        href: https://github.com/giannkas/fundamentals_ml
        aria-label: GitHub
  sidebar: 
    logo: assets/mines_paris_psl_logo.png

toc: true

format:
  html:
    code-link: true
    theme:
      - cosmo
      - brand
      - styles.scss  

execute:
  enable: true
  echo: true
  freeze: auto
  tidy: true